AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128
#      Architectures: ["x86_64"]
      Handler: bootstrap
      Runtime: provided.al2
      Timeout: 5
      CodeUri: target/lambda/rust_lambda_poc/
      PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/lifeway/systems/digitalexperience/aom/aom-primary-permissions-boundary"
      FunctionUrlConfig:
        AuthType: NONE
      Environment:
        Variables:
          RUST_LOG: 3

Outputs:
  FunctionName:
    Value: !Ref HelloWorldFunction
    Description: Name of the Lambda function
  ApiUrl:
    Value:
      Fn::GetAtt: HelloWorldFunctionUrl.FunctionUrl